spring:  
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

      # 컨슈머 Group Id
      group-id: test-group

      # Kafka 서버에 offset이 존재하지 않을 경우 수행할 작업을 설정
      # latest: 가장 최근에 생산된 메시지로 offeset reset
      # earliest: 가장 오래된 메시지로 offeset reset
      # none: offset 정보가 없으면 Exception 발생
      auto-offset-reset: earliest

      # 역직렬화
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # JSON 데이터라면 JsonDeserializer 사용
      # key-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092

      # 직렬화
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      # JSON 데이터라면 JsonDeserializer 사용
      # key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer